apiVersion: v1
kind: Pod
metadata:
  name: volume-pod
spec: 
  containers: 
  - image: busybox 
    name: busybox
    command: ['/bin/sh', '-c', 'while true; do sleep 3600; done']
    volumeMounts:
    - mountPath: /tmp/storage
      name: my-volume
  volumes:
    # This EmptyDir volume will create storage on a node when this pod is assigned to the node. When this pod leaves the node, the storage will also disappear. 
  - name: my-volume
    emptyDir: {}
