apiVersion: v1
kind: Pod
metadata:
  name: my-serviceaccount-pod
spec: 
  serviceAccountName: my-service-account
  containers: 
  - name: my-app-container
    image: busybox
    command: ['sh', '-c' , 'echo Hello Kubernetes && sleep 3600']
