apiVersion: v1
kind: Pod
metadata:
  name: my-readiness-pod
spec:
  containers:
  - name: myapp-container
    image: nginx
    readinessProbe:
      # Can use an HTTP request instead of "exec" with "command" 
      # hit the root endpoint of nginx server. 
      # if request succeeds, container is ready to receive requests. ... what does succeed mean here? is 400 a success? 
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
