apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: my-pvc
spec: 
  storageClassName: local-storage
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests:
      #storage: 2Gi # 2 Gigabytes, will make this incompatible with my-pv
      storage: 512Mi # 512 megabytes

