apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 1Gi
  storageClassName: localdisk
  hostPath:
    path: "/mnt/data"
  accessModes:
    - ReadWriteOnce

