apiVersion: v1
kind: Pod
metadata: 
  name: my-containerport-pod
  labels: 
    app: my-app
    namespace: default
    purpose: container-port
spec: 
  containers: 
  - name: my-app-container
    image: nginx
    ports: 
    - containerPort: 80
