apiVersion: v1
kind: Pod
metadata: 
  name: my-secret-pod
spec: 
  containers: 
  - name: my-app-container
    image: busybox
    command: ['sh', '-c', 'echo Hello & sleep 3600']
    env: 
    - name: MY_PASSWORD
      valueFrom: 
        secretKeyRef: 
          name: my-secret
          key: mykey
    - name: MY_PASSWORD2
      valueFrom: 
        secretKeyRef: 
          name: my-secret
          key: mykey2
